In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('../datasets/train.csv')[['Age','Pclass','Fare','Survived']]

In [3]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [4]:
df.isnull().mean() * 100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [5]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
X_train.head()

      Age  Pclass     Fare
140   NaN       3  15.2458
439  31.0       2  10.5000
817  31.0       2  37.0042
378  20.0       3   4.0125
491  21.0       3   7.2500

In [20]:
# knn_imputer = KNNImputer(n_neighbors=3)
# knn_imputer = KNNImputer(n_neighbors=3, weights='uniform', metric='nan_euclidean')
knn_imputer = KNNImputer(n_neighbors=3, weights='distance', metric='nan_euclidean')
X_train_trf = knn_imputer.fit_transform(X_train)
X_test_trf = knn_imputer.transform(X_test)

In [21]:
X_train_trf[:5]

array([[ 9.00003581,  3.        , 15.2458    ],
       [31.        ,  2.        , 10.5       ],
       [31.        ,  2.        , 37.0042    ],
       [20.        ,  3.        ,  4.0125    ],
       [21.        ,  3.        ,  7.25      ]])

In [23]:
lr = LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.7374301675977654

In [24]:
# Comparision with Simple Imputer --> mean
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [25]:
lr2 = LogisticRegression()
lr2.fit(X_train_trf2, y_train)
y_pred2 = lr2.predict(X_test_trf2)
accuracy_score(y_test, y_pred2)

0.7318435754189944